// Generated by CoffeeScript 1.6.3
(function() {
  var fn, fs, sieve;

  fs = require('fs');

  sieve = function(upperbound) {
    var allprimes, c, k, num, smallPrimes, splitter, _i, _j, _len;
    allprimes = [];
    splitter = Math.floor(Math.sqrt(upperbound));
    if (splitter < 5) {
      smallPrimes = [2, 3];
    } else {
      smallPrimes = sieve(splitter);
    }
    for (num = _i = 5; 5 <= upperbound ? _i <= upperbound : _i >= upperbound; num = 5 <= upperbound ? ++_i : --_i) {
      k = 0;
      for (_j = 0, _len = smallPrimes.length; _j < _len; _j++) {
        c = smallPrimes[_j];
        if (num % c === 0) {
          break;
        }
        ++k;
      }
      if (k === smallPrimes.length) {
        allprimes.push(num);
      }
    }
    return smallPrimes.concat(allprimes);
  };

  fn = "allprimes.txt";

  fs.writeFileSync(fn, sieve(100));

}).call(this);
